apiVersion: apps/v1
kind: Deployment
metadata:
        name: spring-boot-docker-image14
spec:
        selector:
                matchLabels:
                        app: spring-boot-docker-image14
        replicas: 3
        template:
                metadata:
                        labels:
                                app: spring-boot-docker-image14
                spec:
                        containers:
                                - name: spring-boot-docker-image14
                                  image: spring-boot-docker-image14:latest
                                  imagePullPolicy: Never
                                  ports:
                                          - containerPort: 8085