#spring:
#  application:
#    name: spring-mongo-service
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#  data:
#    mongodb:
#      host: '${MONGO_HOST}'
#      database: '${MONGO_DB}'
#      port: 8086
#      username: '${MONGO_USERNAME}'
#      password: '${MONGO_PASSWORD}'
#  cloud:
#    kubernetes:
#      discovery:
#        register: true
#      secrets:
#        name: mongo-secret
#
#      config:
#        enabled: true
#        sources:
#          - namespace: default
#            name: mongo-conf
#      reload:
#        enabled: true
#        mode: polling
#        period: 1000
#management:
#  endpoint:
#    restart:
#      enabled: true
#    health:
#      enabled: true
#    info:
#      enabled: true